# Configuración de servicios que provee la biblioteca.
services:

    # Configuración por defecto de los servicios.
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Paquetes.
    Derafu\Lib\Core\Package\Prime\Contract\PrimePackageInterface:
        class: Derafu\Lib\Core\Package\Prime\PrimePackage

    # Componentes del paquete "prime".
    Derafu\Lib\Core\Package\Prime\Component\Certificate\Contract\CertificateComponentInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Certificate\CertificateComponent
    Derafu\Lib\Core\Package\Prime\Component\Log\Contract\LogComponentInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Log\LogComponent
    Derafu\Lib\Core\Package\Prime\Component\Signature\Contract\SignatureComponentInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Signature\SignatureComponent
    Derafu\Lib\Core\Package\Prime\Component\Xml\Contract\XmlComponentInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Xml\XmlComponent

    # Workers del componente "prime.certificate".
    Derafu\Lib\Core\Package\Prime\Component\Certificate\Contract\FakerWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Certificate\Worker\FakerWorker
    Derafu\Lib\Core\Package\Prime\Component\Certificate\Contract\LoaderWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Certificate\Worker\LoaderWorker
    Derafu\Lib\Core\Package\Prime\Component\Certificate\Contract\ValidatorWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Certificate\Worker\ValidatorWorker

    # Workers del componente "prime.log".
    Derafu\Lib\Core\Package\Prime\Component\Log\Contract\LoggerWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Log\Worker\LoggerWorker

    # Workers del componente "prime.signature".
    Derafu\Lib\Core\Package\Prime\Component\Signature\Contract\GeneratorWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Signature\Worker\GeneratorWorker
    Derafu\Lib\Core\Package\Prime\Component\Signature\Contract\ValidatorWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Signature\Worker\ValidatorWorker

    # Workers del componente "prime.xml".
    Derafu\Lib\Core\Package\Prime\Component\Xml\Contract\EncoderWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Xml\Worker\EncoderWorker
    Derafu\Lib\Core\Package\Prime\Component\Xml\Contract\DecoderWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Xml\Worker\DecoderWorker
    Derafu\Lib\Core\Package\Prime\Component\Xml\Contract\ValidatorWorkerInterface:
        class: Derafu\Lib\Core\Package\Prime\Component\Xml\Worker\ValidatorWorker
